ALTER TABLE actor ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE actor ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE movie ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE movie ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();